// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import {
  activateNextStageApiTournamentsTournamentIdStagesActivatePost,
  changeStatusApiTournamentsTournamentIdChangeStatusPost,
  createMatchApiTournamentsTournamentIdMatchesPost,
  createMultiplePlayersApiTournamentsTournamentIdPlayersMultiPost,
  createMultipleTeamsApiTournamentsTournamentIdTeamsMultiPost,
  createNewClubApiClubsPost,
  createRankingApiTournamentsTournamentIdRankingsPost,
  createRoundApiTournamentsTournamentIdRoundsPost,
  createSinglePlayerApiTournamentsTournamentIdPlayersPost,
  createStageApiTournamentsTournamentIdStagesPost,
  createStageItemApiTournamentsTournamentIdStageItemsPost,
  createTeamApiTournamentsTournamentIdTeamsPost,
  createTournamentApiTournamentsPost,
  deleteClubApiClubsClubIdDelete,
  deleteMatchApiTournamentsTournamentIdMatchesMatchIdDelete,
  deletePlayerApiTournamentsTournamentIdPlayersPlayerIdDelete,
  deleteRankingApiTournamentsTournamentIdRankingsRankingIdDelete,
  deleteRoundApiTournamentsTournamentIdRoundsRoundIdDelete,
  deleteStageApiTournamentsTournamentIdStagesStageIdDelete,
  deleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDelete,
  deleteTeamApiTournamentsTournamentIdTeamsTeamIdDelete,
  deleteTournamentApiTournamentsTournamentIdDelete,
  getAuthFeaturesApiAuthFeaturesGet,
  getAvailableInputsApiTournamentsTournamentIdAvailableInputsGet,
  getClubsApiClubsGet,
  getMeApiUsersUserIdGet,
  getNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGet,
  getPlayersApiTournamentsTournamentIdPlayersGet,
  getRankingsApiTournamentsTournamentIdRankingsGet,
  getStagesApiTournamentsTournamentIdStagesGet,
  getStandingsApiTournamentsTournamentIdStandingsGet,
  getTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoGet,
  getTeamsApiTournamentsTournamentIdTeamsGet,
  getTournamentApiTournamentsTournamentIdGet,
  getTournamentLogoApiTournamentsTournamentIdLogoGet,
  getTournamentsApiTournamentsGet,
  getUserApiUsersMeGet,
  loginForAccessTokenApiTokenPost,
  logoutApiLogoutPost,
  type Options,
  pingApiPingGet,
  putUserPasswordApiUsersUserIdPasswordPut,
  registerUserApiUsersRegisterPost,
  scheduleMatchesApiTournamentsTournamentIdScheduleMatchesPost,
  updateClubApiClubsClubIdPut,
  updateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPut,
  updatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPut,
  updateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPut,
  updateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPut,
  updateStageApiTournamentsTournamentIdStagesStageIdPut,
  updateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPut,
  updateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPut,
  updateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPut,
  updateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPost,
  updateTournamentByIdApiTournamentsTournamentIdPut,
  updateUserDetailsApiUsersUserIdPut,
  uploadLogoApiTournamentsTournamentIdLogoPost,
} from '../sdk.gen';
import type {
  ActivateNextStageApiTournamentsTournamentIdStagesActivatePostData,
  ActivateNextStageApiTournamentsTournamentIdStagesActivatePostError,
  ActivateNextStageApiTournamentsTournamentIdStagesActivatePostResponse,
  ChangeStatusApiTournamentsTournamentIdChangeStatusPostData,
  ChangeStatusApiTournamentsTournamentIdChangeStatusPostError,
  ChangeStatusApiTournamentsTournamentIdChangeStatusPostResponse,
  CreateMatchApiTournamentsTournamentIdMatchesPostData,
  CreateMatchApiTournamentsTournamentIdMatchesPostError,
  CreateMatchApiTournamentsTournamentIdMatchesPostResponse,
  CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostData,
  CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostError,
  CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostResponse,
  CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostData,
  CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostError,
  CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostResponse,
  CreateNewClubApiClubsPostData,
  CreateNewClubApiClubsPostError,
  CreateNewClubApiClubsPostResponse,
  CreateRankingApiTournamentsTournamentIdRankingsPostData,
  CreateRankingApiTournamentsTournamentIdRankingsPostError,
  CreateRankingApiTournamentsTournamentIdRankingsPostResponse,
  CreateRoundApiTournamentsTournamentIdRoundsPostData,
  CreateRoundApiTournamentsTournamentIdRoundsPostError,
  CreateRoundApiTournamentsTournamentIdRoundsPostResponse,
  CreateSinglePlayerApiTournamentsTournamentIdPlayersPostData,
  CreateSinglePlayerApiTournamentsTournamentIdPlayersPostError,
  CreateSinglePlayerApiTournamentsTournamentIdPlayersPostResponse,
  CreateStageApiTournamentsTournamentIdStagesPostData,
  CreateStageApiTournamentsTournamentIdStagesPostError,
  CreateStageApiTournamentsTournamentIdStagesPostResponse,
  CreateStageItemApiTournamentsTournamentIdStageItemsPostData,
  CreateStageItemApiTournamentsTournamentIdStageItemsPostError,
  CreateStageItemApiTournamentsTournamentIdStageItemsPostResponse,
  CreateTeamApiTournamentsTournamentIdTeamsPostData,
  CreateTeamApiTournamentsTournamentIdTeamsPostError,
  CreateTeamApiTournamentsTournamentIdTeamsPostResponse,
  CreateTournamentApiTournamentsPostData,
  CreateTournamentApiTournamentsPostError,
  CreateTournamentApiTournamentsPostResponse,
  DeleteClubApiClubsClubIdDeleteData,
  DeleteClubApiClubsClubIdDeleteError,
  DeleteClubApiClubsClubIdDeleteResponse,
  DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteData,
  DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteError,
  DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteResponse,
  DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteData,
  DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteError,
  DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteResponse,
  DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteData,
  DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteError,
  DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteResponse,
  DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteData,
  DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteError,
  DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteResponse,
  DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteData,
  DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteError,
  DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteResponse,
  DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteData,
  DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteError,
  DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteResponse,
  DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteData,
  DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteError,
  DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteResponse,
  DeleteTournamentApiTournamentsTournamentIdDeleteData,
  DeleteTournamentApiTournamentsTournamentIdDeleteError,
  DeleteTournamentApiTournamentsTournamentIdDeleteResponse,
  GetAuthFeaturesApiAuthFeaturesGetData,
  GetAuthFeaturesApiAuthFeaturesGetResponse,
  GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetData,
  GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetError,
  GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetResponse,
  GetClubsApiClubsGetData,
  GetClubsApiClubsGetResponse,
  GetMeApiUsersUserIdGetData,
  GetMeApiUsersUserIdGetError,
  GetMeApiUsersUserIdGetResponse,
  GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetData,
  GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetError,
  GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetResponse,
  GetPlayersApiTournamentsTournamentIdPlayersGetData,
  GetPlayersApiTournamentsTournamentIdPlayersGetError,
  GetPlayersApiTournamentsTournamentIdPlayersGetResponse,
  GetRankingsApiTournamentsTournamentIdRankingsGetData,
  GetRankingsApiTournamentsTournamentIdRankingsGetError,
  GetRankingsApiTournamentsTournamentIdRankingsGetResponse,
  GetStagesApiTournamentsTournamentIdStagesGetData,
  GetStagesApiTournamentsTournamentIdStagesGetError,
  GetStagesApiTournamentsTournamentIdStagesGetResponse,
  GetStandingsApiTournamentsTournamentIdStandingsGetData,
  GetStandingsApiTournamentsTournamentIdStandingsGetError,
  GetStandingsApiTournamentsTournamentIdStandingsGetResponse,
  GetTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoGetData,
  GetTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoGetError,
  GetTeamsApiTournamentsTournamentIdTeamsGetData,
  GetTeamsApiTournamentsTournamentIdTeamsGetError,
  GetTeamsApiTournamentsTournamentIdTeamsGetResponse,
  GetTournamentApiTournamentsTournamentIdGetData,
  GetTournamentApiTournamentsTournamentIdGetError,
  GetTournamentApiTournamentsTournamentIdGetResponse,
  GetTournamentLogoApiTournamentsTournamentIdLogoGetData,
  GetTournamentLogoApiTournamentsTournamentIdLogoGetError,
  GetTournamentsApiTournamentsGetData,
  GetTournamentsApiTournamentsGetError,
  GetTournamentsApiTournamentsGetResponse,
  GetUserApiUsersMeGetData,
  GetUserApiUsersMeGetResponse,
  LoginForAccessTokenApiTokenPostData,
  LoginForAccessTokenApiTokenPostError,
  LoginForAccessTokenApiTokenPostResponse,
  LogoutApiLogoutPostData,
  LogoutApiLogoutPostResponse,
  PingApiPingGetData,
  PingApiPingGetResponse,
  PutUserPasswordApiUsersUserIdPasswordPutData,
  PutUserPasswordApiUsersUserIdPasswordPutError,
  PutUserPasswordApiUsersUserIdPasswordPutResponse,
  RegisterUserApiUsersRegisterPostData,
  RegisterUserApiUsersRegisterPostError,
  RegisterUserApiUsersRegisterPostResponse,
  ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostData,
  ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostError,
  ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostResponse,
  UpdateClubApiClubsClubIdPutData,
  UpdateClubApiClubsClubIdPutError,
  UpdateClubApiClubsClubIdPutResponse,
  UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutData,
  UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutError,
  UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutResponse,
  UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutData,
  UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutError,
  UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutResponse,
  UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutData,
  UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutError,
  UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutResponse,
  UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutData,
  UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutError,
  UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutResponse,
  UpdateStageApiTournamentsTournamentIdStagesStageIdPutData,
  UpdateStageApiTournamentsTournamentIdStagesStageIdPutError,
  UpdateStageApiTournamentsTournamentIdStagesStageIdPutResponse,
  UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutData,
  UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutError,
  UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutResponse,
  UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutData,
  UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutError,
  UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponse,
  UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutData,
  UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutError,
  UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutResponse,
  UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostData,
  UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostError,
  UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostResponse,
  UpdateTournamentByIdApiTournamentsTournamentIdPutData,
  UpdateTournamentByIdApiTournamentsTournamentIdPutError,
  UpdateTournamentByIdApiTournamentsTournamentIdPutResponse,
  UpdateUserDetailsApiUsersUserIdPutData,
  UpdateUserDetailsApiUsersUserIdPutError,
  UpdateUserDetailsApiUsersUserIdPutResponse,
  UploadLogoApiTournamentsTournamentIdLogoPostData,
  UploadLogoApiTournamentsTournamentIdLogoPostError,
  UploadLogoApiTournamentsTournamentIdLogoPostResponse,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getAuthFeaturesApiAuthFeaturesGetQueryKey = (
  options?: Options<GetAuthFeaturesApiAuthFeaturesGetData>,
) => createQueryKey('getAuthFeaturesApiAuthFeaturesGet', options);

/**
 * Get Auth Features
 */
export const getAuthFeaturesApiAuthFeaturesGetOptions = (
  options?: Options<GetAuthFeaturesApiAuthFeaturesGetData>,
) =>
  queryOptions<
    GetAuthFeaturesApiAuthFeaturesGetResponse,
    AxiosError<DefaultError>,
    GetAuthFeaturesApiAuthFeaturesGetResponse,
    ReturnType<typeof getAuthFeaturesApiAuthFeaturesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAuthFeaturesApiAuthFeaturesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAuthFeaturesApiAuthFeaturesGetQueryKey(options),
  });

export const getClubsApiClubsGetQueryKey = (options?: Options<GetClubsApiClubsGetData>) =>
  createQueryKey('getClubsApiClubsGet', options);

/**
 * Get Clubs
 */
export const getClubsApiClubsGetOptions = (options?: Options<GetClubsApiClubsGetData>) =>
  queryOptions<
    GetClubsApiClubsGetResponse,
    AxiosError<DefaultError>,
    GetClubsApiClubsGetResponse,
    ReturnType<typeof getClubsApiClubsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getClubsApiClubsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getClubsApiClubsGetQueryKey(options),
  });

/**
 * Create New Club
 */
export const createNewClubApiClubsPostMutation = (
  options?: Partial<Options<CreateNewClubApiClubsPostData>>,
): UseMutationOptions<
  CreateNewClubApiClubsPostResponse,
  AxiosError<CreateNewClubApiClubsPostError>,
  Options<CreateNewClubApiClubsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateNewClubApiClubsPostResponse,
    AxiosError<CreateNewClubApiClubsPostError>,
    Options<CreateNewClubApiClubsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createNewClubApiClubsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Club
 */
export const deleteClubApiClubsClubIdDeleteMutation = (
  options?: Partial<Options<DeleteClubApiClubsClubIdDeleteData>>,
): UseMutationOptions<
  DeleteClubApiClubsClubIdDeleteResponse,
  AxiosError<DeleteClubApiClubsClubIdDeleteError>,
  Options<DeleteClubApiClubsClubIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteClubApiClubsClubIdDeleteResponse,
    AxiosError<DeleteClubApiClubsClubIdDeleteError>,
    Options<DeleteClubApiClubsClubIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteClubApiClubsClubIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Club
 */
export const updateClubApiClubsClubIdPutMutation = (
  options?: Partial<Options<UpdateClubApiClubsClubIdPutData>>,
): UseMutationOptions<
  UpdateClubApiClubsClubIdPutResponse,
  AxiosError<UpdateClubApiClubsClubIdPutError>,
  Options<UpdateClubApiClubsClubIdPutData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateClubApiClubsClubIdPutResponse,
    AxiosError<UpdateClubApiClubsClubIdPutError>,
    Options<UpdateClubApiClubsClubIdPutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateClubApiClubsClubIdPut({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Logout
 *
 * Ends the session in this browser by removing its cookie.
 */
export const logoutApiLogoutPostMutation = (
  options?: Partial<Options<LogoutApiLogoutPostData>>,
): UseMutationOptions<
  LogoutApiLogoutPostResponse,
  AxiosError<DefaultError>,
  Options<LogoutApiLogoutPostData>
> => {
  const mutationOptions: UseMutationOptions<
    LogoutApiLogoutPostResponse,
    AxiosError<DefaultError>,
    Options<LogoutApiLogoutPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await logoutApiLogoutPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const pingApiPingGetQueryKey = (options?: Options<PingApiPingGetData>) =>
  createQueryKey('pingApiPingGet', options);

/**
 * Healthcheck ping
 */
export const pingApiPingGetOptions = (options?: Options<PingApiPingGetData>) =>
  queryOptions<
    PingApiPingGetResponse,
    AxiosError<DefaultError>,
    PingApiPingGetResponse,
    ReturnType<typeof pingApiPingGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await pingApiPingGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: pingApiPingGetQueryKey(options),
  });

/**
 * Login For Access Token
 */
export const loginForAccessTokenApiTokenPostMutation = (
  options?: Partial<Options<LoginForAccessTokenApiTokenPostData>>,
): UseMutationOptions<
  LoginForAccessTokenApiTokenPostResponse,
  AxiosError<LoginForAccessTokenApiTokenPostError>,
  Options<LoginForAccessTokenApiTokenPostData>
> => {
  const mutationOptions: UseMutationOptions<
    LoginForAccessTokenApiTokenPostResponse,
    AxiosError<LoginForAccessTokenApiTokenPostError>,
    Options<LoginForAccessTokenApiTokenPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await loginForAccessTokenApiTokenPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getTournamentsApiTournamentsGetQueryKey = (
  options?: Options<GetTournamentsApiTournamentsGetData>,
) => createQueryKey('getTournamentsApiTournamentsGet', options);

/**
 * Get Tournaments
 */
export const getTournamentsApiTournamentsGetOptions = (
  options?: Options<GetTournamentsApiTournamentsGetData>,
) =>
  queryOptions<
    GetTournamentsApiTournamentsGetResponse,
    AxiosError<GetTournamentsApiTournamentsGetError>,
    GetTournamentsApiTournamentsGetResponse,
    ReturnType<typeof getTournamentsApiTournamentsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTournamentsApiTournamentsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTournamentsApiTournamentsGetQueryKey(options),
  });

/**
 * Create Tournament
 */
export const createTournamentApiTournamentsPostMutation = (
  options?: Partial<Options<CreateTournamentApiTournamentsPostData>>,
): UseMutationOptions<
  CreateTournamentApiTournamentsPostResponse,
  AxiosError<CreateTournamentApiTournamentsPostError>,
  Options<CreateTournamentApiTournamentsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateTournamentApiTournamentsPostResponse,
    AxiosError<CreateTournamentApiTournamentsPostError>,
    Options<CreateTournamentApiTournamentsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createTournamentApiTournamentsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Tournament
 */
export const deleteTournamentApiTournamentsTournamentIdDeleteMutation = (
  options?: Partial<Options<DeleteTournamentApiTournamentsTournamentIdDeleteData>>,
): UseMutationOptions<
  DeleteTournamentApiTournamentsTournamentIdDeleteResponse,
  AxiosError<DeleteTournamentApiTournamentsTournamentIdDeleteError>,
  Options<DeleteTournamentApiTournamentsTournamentIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteTournamentApiTournamentsTournamentIdDeleteResponse,
    AxiosError<DeleteTournamentApiTournamentsTournamentIdDeleteError>,
    Options<DeleteTournamentApiTournamentsTournamentIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteTournamentApiTournamentsTournamentIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getTournamentApiTournamentsTournamentIdGetQueryKey = (
  options: Options<GetTournamentApiTournamentsTournamentIdGetData>,
) => createQueryKey('getTournamentApiTournamentsTournamentIdGet', options);

/**
 * Get Tournament
 */
export const getTournamentApiTournamentsTournamentIdGetOptions = (
  options: Options<GetTournamentApiTournamentsTournamentIdGetData>,
) =>
  queryOptions<
    GetTournamentApiTournamentsTournamentIdGetResponse,
    AxiosError<GetTournamentApiTournamentsTournamentIdGetError>,
    GetTournamentApiTournamentsTournamentIdGetResponse,
    ReturnType<typeof getTournamentApiTournamentsTournamentIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTournamentApiTournamentsTournamentIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTournamentApiTournamentsTournamentIdGetQueryKey(options),
  });

/**
 * Update Tournament By Id
 */
export const updateTournamentByIdApiTournamentsTournamentIdPutMutation = (
  options?: Partial<Options<UpdateTournamentByIdApiTournamentsTournamentIdPutData>>,
): UseMutationOptions<
  UpdateTournamentByIdApiTournamentsTournamentIdPutResponse,
  AxiosError<UpdateTournamentByIdApiTournamentsTournamentIdPutError>,
  Options<UpdateTournamentByIdApiTournamentsTournamentIdPutData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateTournamentByIdApiTournamentsTournamentIdPutResponse,
    AxiosError<UpdateTournamentByIdApiTournamentsTournamentIdPutError>,
    Options<UpdateTournamentByIdApiTournamentsTournamentIdPutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateTournamentByIdApiTournamentsTournamentIdPut({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAvailableInputsApiTournamentsTournamentIdAvailableInputsGetQueryKey = (
  options: Options<GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetData>,
) => createQueryKey('getAvailableInputsApiTournamentsTournamentIdAvailableInputsGet', options);

/**
 * Get Available Inputs
 */
export const getAvailableInputsApiTournamentsTournamentIdAvailableInputsGetOptions = (
  options: Options<GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetData>,
) =>
  queryOptions<
    GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetResponse,
    AxiosError<GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetError>,
    GetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetResponse,
    ReturnType<typeof getAvailableInputsApiTournamentsTournamentIdAvailableInputsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAvailableInputsApiTournamentsTournamentIdAvailableInputsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAvailableInputsApiTournamentsTournamentIdAvailableInputsGetQueryKey(options),
  });

/**
 * Change Status
 *
 * Make a tournament archived or non-archived.
 */
export const changeStatusApiTournamentsTournamentIdChangeStatusPostMutation = (
  options?: Partial<Options<ChangeStatusApiTournamentsTournamentIdChangeStatusPostData>>,
): UseMutationOptions<
  ChangeStatusApiTournamentsTournamentIdChangeStatusPostResponse,
  AxiosError<ChangeStatusApiTournamentsTournamentIdChangeStatusPostError>,
  Options<ChangeStatusApiTournamentsTournamentIdChangeStatusPostData>
> => {
  const mutationOptions: UseMutationOptions<
    ChangeStatusApiTournamentsTournamentIdChangeStatusPostResponse,
    AxiosError<ChangeStatusApiTournamentsTournamentIdChangeStatusPostError>,
    Options<ChangeStatusApiTournamentsTournamentIdChangeStatusPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await changeStatusApiTournamentsTournamentIdChangeStatusPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getTournamentLogoApiTournamentsTournamentIdLogoGetQueryKey = (
  options: Options<GetTournamentLogoApiTournamentsTournamentIdLogoGetData>,
) => createQueryKey('getTournamentLogoApiTournamentsTournamentIdLogoGet', options);

/**
 * Get Tournament Logo
 */
export const getTournamentLogoApiTournamentsTournamentIdLogoGetOptions = (
  options: Options<GetTournamentLogoApiTournamentsTournamentIdLogoGetData>,
) =>
  queryOptions<
    unknown,
    AxiosError<GetTournamentLogoApiTournamentsTournamentIdLogoGetError>,
    unknown,
    ReturnType<typeof getTournamentLogoApiTournamentsTournamentIdLogoGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTournamentLogoApiTournamentsTournamentIdLogoGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTournamentLogoApiTournamentsTournamentIdLogoGetQueryKey(options),
  });

/**
 * Upload Logo
 */
export const uploadLogoApiTournamentsTournamentIdLogoPostMutation = (
  options?: Partial<Options<UploadLogoApiTournamentsTournamentIdLogoPostData>>,
): UseMutationOptions<
  UploadLogoApiTournamentsTournamentIdLogoPostResponse,
  AxiosError<UploadLogoApiTournamentsTournamentIdLogoPostError>,
  Options<UploadLogoApiTournamentsTournamentIdLogoPostData>
> => {
  const mutationOptions: UseMutationOptions<
    UploadLogoApiTournamentsTournamentIdLogoPostResponse,
    AxiosError<UploadLogoApiTournamentsTournamentIdLogoPostError>,
    Options<UploadLogoApiTournamentsTournamentIdLogoPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await uploadLogoApiTournamentsTournamentIdLogoPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Create Match
 */
export const createMatchApiTournamentsTournamentIdMatchesPostMutation = (
  options?: Partial<Options<CreateMatchApiTournamentsTournamentIdMatchesPostData>>,
): UseMutationOptions<
  CreateMatchApiTournamentsTournamentIdMatchesPostResponse,
  AxiosError<CreateMatchApiTournamentsTournamentIdMatchesPostError>,
  Options<CreateMatchApiTournamentsTournamentIdMatchesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateMatchApiTournamentsTournamentIdMatchesPostResponse,
    AxiosError<CreateMatchApiTournamentsTournamentIdMatchesPostError>,
    Options<CreateMatchApiTournamentsTournamentIdMatchesPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createMatchApiTournamentsTournamentIdMatchesPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Match
 */
export const deleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteMutation = (
  options?: Partial<Options<DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteData>>,
): UseMutationOptions<
  DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteResponse,
  AxiosError<DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteError>,
  Options<DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteResponse,
    AxiosError<DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteError>,
    Options<DeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteMatchApiTournamentsTournamentIdMatchesMatchIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Match By Id
 */
export const updateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutMutation = (
  options?: Partial<Options<UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutData>>,
): UseMutationOptions<
  UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutResponse,
  AxiosError<UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutError>,
  Options<UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutResponse,
    AxiosError<UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutError>,
    Options<UpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPut({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetQueryKey = (
  options: Options<GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetData>,
) => createQueryKey('getNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGet', options);

/**
 * Get Next Stage Rankings
 *
 * Get the rankings for the stage items in this stage.
 */
export const getNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetOptions = (
  options: Options<GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetData>,
) =>
  queryOptions<
    GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetResponse,
    AxiosError<GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetError>,
    GetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetResponse,
    ReturnType<typeof getNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetQueryKey(options),
  });

export const getPlayersApiTournamentsTournamentIdPlayersGetQueryKey = (
  options: Options<GetPlayersApiTournamentsTournamentIdPlayersGetData>,
) => createQueryKey('getPlayersApiTournamentsTournamentIdPlayersGet', options);

/**
 * Get Players
 */
export const getPlayersApiTournamentsTournamentIdPlayersGetOptions = (
  options: Options<GetPlayersApiTournamentsTournamentIdPlayersGetData>,
) =>
  queryOptions<
    GetPlayersApiTournamentsTournamentIdPlayersGetResponse,
    AxiosError<GetPlayersApiTournamentsTournamentIdPlayersGetError>,
    GetPlayersApiTournamentsTournamentIdPlayersGetResponse,
    ReturnType<typeof getPlayersApiTournamentsTournamentIdPlayersGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPlayersApiTournamentsTournamentIdPlayersGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPlayersApiTournamentsTournamentIdPlayersGetQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getPlayersApiTournamentsTournamentIdPlayersGetInfiniteQueryKey = (
  options: Options<GetPlayersApiTournamentsTournamentIdPlayersGetData>,
): QueryKey<Options<GetPlayersApiTournamentsTournamentIdPlayersGetData>> =>
  createQueryKey('getPlayersApiTournamentsTournamentIdPlayersGet', options, true);

/**
 * Get Players
 */
export const getPlayersApiTournamentsTournamentIdPlayersGetInfiniteOptions = (
  options: Options<GetPlayersApiTournamentsTournamentIdPlayersGetData>,
) => {
  const opts = infiniteQueryOptions<
    GetPlayersApiTournamentsTournamentIdPlayersGetResponse,
    AxiosError<GetPlayersApiTournamentsTournamentIdPlayersGetError>,
    InfiniteData<GetPlayersApiTournamentsTournamentIdPlayersGetResponse>,
    QueryKey<Options<GetPlayersApiTournamentsTournamentIdPlayersGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetPlayersApiTournamentsTournamentIdPlayersGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetPlayersApiTournamentsTournamentIdPlayersGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getPlayersApiTournamentsTournamentIdPlayersGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getPlayersApiTournamentsTournamentIdPlayersGetInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * Create Single Player
 */
export const createSinglePlayerApiTournamentsTournamentIdPlayersPostMutation = (
  options?: Partial<Options<CreateSinglePlayerApiTournamentsTournamentIdPlayersPostData>>,
): UseMutationOptions<
  CreateSinglePlayerApiTournamentsTournamentIdPlayersPostResponse,
  AxiosError<CreateSinglePlayerApiTournamentsTournamentIdPlayersPostError>,
  Options<CreateSinglePlayerApiTournamentsTournamentIdPlayersPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateSinglePlayerApiTournamentsTournamentIdPlayersPostResponse,
    AxiosError<CreateSinglePlayerApiTournamentsTournamentIdPlayersPostError>,
    Options<CreateSinglePlayerApiTournamentsTournamentIdPlayersPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createSinglePlayerApiTournamentsTournamentIdPlayersPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Player
 */
export const deletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteMutation = (
  options?: Partial<Options<DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteData>>,
): UseMutationOptions<
  DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteResponse,
  AxiosError<DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteError>,
  Options<DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteResponse,
    AxiosError<DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteError>,
    Options<DeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deletePlayerApiTournamentsTournamentIdPlayersPlayerIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Player By Id
 */
export const updatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutMutation = (
  options?: Partial<Options<UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutData>>,
): UseMutationOptions<
  UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutResponse,
  AxiosError<UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutError>,
  Options<UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutResponse,
    AxiosError<UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutError>,
    Options<UpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPut({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Create Multiple Players
 */
export const createMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostMutation = (
  options?: Partial<Options<CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostData>>,
): UseMutationOptions<
  CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostResponse,
  AxiosError<CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostError>,
  Options<CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostResponse,
    AxiosError<CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostError>,
    Options<CreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createMultiplePlayersApiTournamentsTournamentIdPlayersMultiPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getRankingsApiTournamentsTournamentIdRankingsGetQueryKey = (
  options: Options<GetRankingsApiTournamentsTournamentIdRankingsGetData>,
) => createQueryKey('getRankingsApiTournamentsTournamentIdRankingsGet', options);

/**
 * Get Rankings
 */
export const getRankingsApiTournamentsTournamentIdRankingsGetOptions = (
  options: Options<GetRankingsApiTournamentsTournamentIdRankingsGetData>,
) =>
  queryOptions<
    GetRankingsApiTournamentsTournamentIdRankingsGetResponse,
    AxiosError<GetRankingsApiTournamentsTournamentIdRankingsGetError>,
    GetRankingsApiTournamentsTournamentIdRankingsGetResponse,
    ReturnType<typeof getRankingsApiTournamentsTournamentIdRankingsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRankingsApiTournamentsTournamentIdRankingsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRankingsApiTournamentsTournamentIdRankingsGetQueryKey(options),
  });

/**
 * Create Ranking
 */
export const createRankingApiTournamentsTournamentIdRankingsPostMutation = (
  options?: Partial<Options<CreateRankingApiTournamentsTournamentIdRankingsPostData>>,
): UseMutationOptions<
  CreateRankingApiTournamentsTournamentIdRankingsPostResponse,
  AxiosError<CreateRankingApiTournamentsTournamentIdRankingsPostError>,
  Options<CreateRankingApiTournamentsTournamentIdRankingsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateRankingApiTournamentsTournamentIdRankingsPostResponse,
    AxiosError<CreateRankingApiTournamentsTournamentIdRankingsPostError>,
    Options<CreateRankingApiTournamentsTournamentIdRankingsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createRankingApiTournamentsTournamentIdRankingsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Ranking
 */
export const deleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteMutation = (
  options?: Partial<Options<DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteData>>,
): UseMutationOptions<
  DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteResponse,
  AxiosError<DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteError>,
  Options<DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteResponse,
    AxiosError<DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteError>,
    Options<DeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteRankingApiTournamentsTournamentIdRankingsRankingIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Ranking By Id
 */
export const updateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutMutation = (
  options?: Partial<Options<UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutData>>,
): UseMutationOptions<
  UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutResponse,
  AxiosError<UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutError>,
  Options<UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutResponse,
    AxiosError<UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutError>,
    Options<UpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPut({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Create Round
 *
 * Create the next round of a Swiss stage item as a draft in which every active team is paired.
 *
 * Only organizers see the draft. Its pairings can be changed by adding and deleting matches, and
 * it is published by updating the round with `is_draft` set to false.
 */
export const createRoundApiTournamentsTournamentIdRoundsPostMutation = (
  options?: Partial<Options<CreateRoundApiTournamentsTournamentIdRoundsPostData>>,
): UseMutationOptions<
  CreateRoundApiTournamentsTournamentIdRoundsPostResponse,
  AxiosError<CreateRoundApiTournamentsTournamentIdRoundsPostError>,
  Options<CreateRoundApiTournamentsTournamentIdRoundsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateRoundApiTournamentsTournamentIdRoundsPostResponse,
    AxiosError<CreateRoundApiTournamentsTournamentIdRoundsPostError>,
    Options<CreateRoundApiTournamentsTournamentIdRoundsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createRoundApiTournamentsTournamentIdRoundsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Round
 */
export const deleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteMutation = (
  options?: Partial<Options<DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteData>>,
): UseMutationOptions<
  DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteResponse,
  AxiosError<DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteError>,
  Options<DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteResponse,
    AxiosError<DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteError>,
    Options<DeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteRoundApiTournamentsTournamentIdRoundsRoundIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Round By Id
 */
export const updateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutMutation = (
  options?: Partial<Options<UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutData>>,
): UseMutationOptions<
  UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutResponse,
  AxiosError<UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutError>,
  Options<UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutResponse,
    AxiosError<UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutError>,
    Options<UpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPut({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Schedule Matches
 */
export const scheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostMutation = (
  options?: Partial<Options<ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostData>>,
): UseMutationOptions<
  ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostResponse,
  AxiosError<ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostError>,
  Options<ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostResponse,
    AxiosError<ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostError>,
    Options<ScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await scheduleMatchesApiTournamentsTournamentIdScheduleMatchesPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Create Stage Item
 */
export const createStageItemApiTournamentsTournamentIdStageItemsPostMutation = (
  options?: Partial<Options<CreateStageItemApiTournamentsTournamentIdStageItemsPostData>>,
): UseMutationOptions<
  CreateStageItemApiTournamentsTournamentIdStageItemsPostResponse,
  AxiosError<CreateStageItemApiTournamentsTournamentIdStageItemsPostError>,
  Options<CreateStageItemApiTournamentsTournamentIdStageItemsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateStageItemApiTournamentsTournamentIdStageItemsPostResponse,
    AxiosError<CreateStageItemApiTournamentsTournamentIdStageItemsPostError>,
    Options<CreateStageItemApiTournamentsTournamentIdStageItemsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createStageItemApiTournamentsTournamentIdStageItemsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Stage Item
 */
export const deleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteMutation = (
  options?: Partial<
    Options<DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteData>
  >,
): UseMutationOptions<
  DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteResponse,
  AxiosError<DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteError>,
  Options<DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteResponse,
    AxiosError<DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteError>,
    Options<DeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Stage Item
 */
export const updateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutMutation = (
  options?: Partial<Options<UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutData>>,
): UseMutationOptions<
  UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutResponse,
  AxiosError<UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutError>,
  Options<UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutResponse,
    AxiosError<UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutError>,
    Options<UpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPut({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Stage Item Input
 */
export const updateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutMutation =
  (
    options?: Partial<
      Options<UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutData>
    >,
  ): UseMutationOptions<
    UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponse,
    AxiosError<UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutError>,
    Options<UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutData>
  > => {
    const mutationOptions: UseMutationOptions<
      UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponse,
      AxiosError<UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutError>,
      Options<UpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await updateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPut(
            {
              ...options,
              ...fnOptions,
              throwOnError: true,
            },
          );
        return data;
      },
    };
    return mutationOptions;
  };

export const getStagesApiTournamentsTournamentIdStagesGetQueryKey = (
  options: Options<GetStagesApiTournamentsTournamentIdStagesGetData>,
) => createQueryKey('getStagesApiTournamentsTournamentIdStagesGet', options);

/**
 * Get Stages
 */
export const getStagesApiTournamentsTournamentIdStagesGetOptions = (
  options: Options<GetStagesApiTournamentsTournamentIdStagesGetData>,
) =>
  queryOptions<
    GetStagesApiTournamentsTournamentIdStagesGetResponse,
    AxiosError<GetStagesApiTournamentsTournamentIdStagesGetError>,
    GetStagesApiTournamentsTournamentIdStagesGetResponse,
    ReturnType<typeof getStagesApiTournamentsTournamentIdStagesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getStagesApiTournamentsTournamentIdStagesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getStagesApiTournamentsTournamentIdStagesGetQueryKey(options),
  });

/**
 * Create Stage
 */
export const createStageApiTournamentsTournamentIdStagesPostMutation = (
  options?: Partial<Options<CreateStageApiTournamentsTournamentIdStagesPostData>>,
): UseMutationOptions<
  CreateStageApiTournamentsTournamentIdStagesPostResponse,
  AxiosError<CreateStageApiTournamentsTournamentIdStagesPostError>,
  Options<CreateStageApiTournamentsTournamentIdStagesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateStageApiTournamentsTournamentIdStagesPostResponse,
    AxiosError<CreateStageApiTournamentsTournamentIdStagesPostError>,
    Options<CreateStageApiTournamentsTournamentIdStagesPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createStageApiTournamentsTournamentIdStagesPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Activate Next Stage
 */
export const activateNextStageApiTournamentsTournamentIdStagesActivatePostMutation = (
  options?: Partial<Options<ActivateNextStageApiTournamentsTournamentIdStagesActivatePostData>>,
): UseMutationOptions<
  ActivateNextStageApiTournamentsTournamentIdStagesActivatePostResponse,
  AxiosError<ActivateNextStageApiTournamentsTournamentIdStagesActivatePostError>,
  Options<ActivateNextStageApiTournamentsTournamentIdStagesActivatePostData>
> => {
  const mutationOptions: UseMutationOptions<
    ActivateNextStageApiTournamentsTournamentIdStagesActivatePostResponse,
    AxiosError<ActivateNextStageApiTournamentsTournamentIdStagesActivatePostError>,
    Options<ActivateNextStageApiTournamentsTournamentIdStagesActivatePostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await activateNextStageApiTournamentsTournamentIdStagesActivatePost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Stage
 */
export const deleteStageApiTournamentsTournamentIdStagesStageIdDeleteMutation = (
  options?: Partial<Options<DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteData>>,
): UseMutationOptions<
  DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteResponse,
  AxiosError<DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteError>,
  Options<DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteResponse,
    AxiosError<DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteError>,
    Options<DeleteStageApiTournamentsTournamentIdStagesStageIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteStageApiTournamentsTournamentIdStagesStageIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Stage
 */
export const updateStageApiTournamentsTournamentIdStagesStageIdPutMutation = (
  options?: Partial<Options<UpdateStageApiTournamentsTournamentIdStagesStageIdPutData>>,
): UseMutationOptions<
  UpdateStageApiTournamentsTournamentIdStagesStageIdPutResponse,
  AxiosError<UpdateStageApiTournamentsTournamentIdStagesStageIdPutError>,
  Options<UpdateStageApiTournamentsTournamentIdStagesStageIdPutData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateStageApiTournamentsTournamentIdStagesStageIdPutResponse,
    AxiosError<UpdateStageApiTournamentsTournamentIdStagesStageIdPutError>,
    Options<UpdateStageApiTournamentsTournamentIdStagesStageIdPutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateStageApiTournamentsTournamentIdStagesStageIdPut({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getStandingsApiTournamentsTournamentIdStandingsGetQueryKey = (
  options: Options<GetStandingsApiTournamentsTournamentIdStandingsGetData>,
) => createQueryKey('getStandingsApiTournamentsTournamentIdStandingsGet', options);

/**
 * Get Standings
 *
 * Get the teams of every stage item, best first. Teams advance to the next stage in this order.
 */
export const getStandingsApiTournamentsTournamentIdStandingsGetOptions = (
  options: Options<GetStandingsApiTournamentsTournamentIdStandingsGetData>,
) =>
  queryOptions<
    GetStandingsApiTournamentsTournamentIdStandingsGetResponse,
    AxiosError<GetStandingsApiTournamentsTournamentIdStandingsGetError>,
    GetStandingsApiTournamentsTournamentIdStandingsGetResponse,
    ReturnType<typeof getStandingsApiTournamentsTournamentIdStandingsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getStandingsApiTournamentsTournamentIdStandingsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getStandingsApiTournamentsTournamentIdStandingsGetQueryKey(options),
  });

export const getTeamsApiTournamentsTournamentIdTeamsGetQueryKey = (
  options: Options<GetTeamsApiTournamentsTournamentIdTeamsGetData>,
) => createQueryKey('getTeamsApiTournamentsTournamentIdTeamsGet', options);

/**
 * Get Teams
 */
export const getTeamsApiTournamentsTournamentIdTeamsGetOptions = (
  options: Options<GetTeamsApiTournamentsTournamentIdTeamsGetData>,
) =>
  queryOptions<
    GetTeamsApiTournamentsTournamentIdTeamsGetResponse,
    AxiosError<GetTeamsApiTournamentsTournamentIdTeamsGetError>,
    GetTeamsApiTournamentsTournamentIdTeamsGetResponse,
    ReturnType<typeof getTeamsApiTournamentsTournamentIdTeamsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamsApiTournamentsTournamentIdTeamsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamsApiTournamentsTournamentIdTeamsGetQueryKey(options),
  });

export const getTeamsApiTournamentsTournamentIdTeamsGetInfiniteQueryKey = (
  options: Options<GetTeamsApiTournamentsTournamentIdTeamsGetData>,
): QueryKey<Options<GetTeamsApiTournamentsTournamentIdTeamsGetData>> =>
  createQueryKey('getTeamsApiTournamentsTournamentIdTeamsGet', options, true);

/**
 * Get Teams
 */
export const getTeamsApiTournamentsTournamentIdTeamsGetInfiniteOptions = (
  options: Options<GetTeamsApiTournamentsTournamentIdTeamsGetData>,
) => {
  const opts = infiniteQueryOptions<
    GetTeamsApiTournamentsTournamentIdTeamsGetResponse,
    AxiosError<GetTeamsApiTournamentsTournamentIdTeamsGetError>,
    InfiniteData<GetTeamsApiTournamentsTournamentIdTeamsGetResponse>,
    QueryKey<Options<GetTeamsApiTournamentsTournamentIdTeamsGetData>>,
    | number
    | Pick<
        QueryKey<Options<GetTeamsApiTournamentsTournamentIdTeamsGetData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetTeamsApiTournamentsTournamentIdTeamsGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getTeamsApiTournamentsTournamentIdTeamsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getTeamsApiTournamentsTournamentIdTeamsGetInfiniteQueryKey(options),
    },
  );
  return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * Create Team
 */
export const createTeamApiTournamentsTournamentIdTeamsPostMutation = (
  options?: Partial<Options<CreateTeamApiTournamentsTournamentIdTeamsPostData>>,
): UseMutationOptions<
  CreateTeamApiTournamentsTournamentIdTeamsPostResponse,
  AxiosError<CreateTeamApiTournamentsTournamentIdTeamsPostError>,
  Options<CreateTeamApiTournamentsTournamentIdTeamsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateTeamApiTournamentsTournamentIdTeamsPostResponse,
    AxiosError<CreateTeamApiTournamentsTournamentIdTeamsPostError>,
    Options<CreateTeamApiTournamentsTournamentIdTeamsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createTeamApiTournamentsTournamentIdTeamsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Team
 */
export const deleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteMutation = (
  options?: Partial<Options<DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteData>>,
): UseMutationOptions<
  DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteResponse,
  AxiosError<DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteError>,
  Options<DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteResponse,
    AxiosError<DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteError>,
    Options<DeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteTeamApiTournamentsTournamentIdTeamsTeamIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Team By Id
 */
export const updateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutMutation = (
  options?: Partial<Options<UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutData>>,
): UseMutationOptions<
  UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutResponse,
  AxiosError<UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutError>,
  Options<UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutResponse,
    AxiosError<UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutError>,
    Options<UpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPut({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoGetQueryKey = (
  options: Options<GetTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoGetData>,
) => createQueryKey('getTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoGet', options);

/**
 * Get Team Logo
 */
export const getTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoGetOptions = (
  options: Options<GetTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoGetData>,
) =>
  queryOptions<
    unknown,
    AxiosError<GetTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoGetError>,
    unknown,
    ReturnType<typeof getTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoGetQueryKey(options),
  });

/**
 * Update Team Logo
 */
export const updateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostMutation = (
  options?: Partial<Options<UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostData>>,
): UseMutationOptions<
  UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostResponse,
  AxiosError<UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostError>,
  Options<UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostResponse,
    AxiosError<UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostError>,
    Options<UpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Create Multiple Teams
 */
export const createMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostMutation = (
  options?: Partial<Options<CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostData>>,
): UseMutationOptions<
  CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostResponse,
  AxiosError<CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostError>,
  Options<CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostResponse,
    AxiosError<CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostError>,
    Options<CreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createMultipleTeamsApiTournamentsTournamentIdTeamsMultiPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getUserApiUsersMeGetQueryKey = (options?: Options<GetUserApiUsersMeGetData>) =>
  createQueryKey('getUserApiUsersMeGet', options);

/**
 * Get User
 */
export const getUserApiUsersMeGetOptions = (options?: Options<GetUserApiUsersMeGetData>) =>
  queryOptions<
    GetUserApiUsersMeGetResponse,
    AxiosError<DefaultError>,
    GetUserApiUsersMeGetResponse,
    ReturnType<typeof getUserApiUsersMeGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserApiUsersMeGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUserApiUsersMeGetQueryKey(options),
  });

/**
 * Register User
 */
export const registerUserApiUsersRegisterPostMutation = (
  options?: Partial<Options<RegisterUserApiUsersRegisterPostData>>,
): UseMutationOptions<
  RegisterUserApiUsersRegisterPostResponse,
  AxiosError<RegisterUserApiUsersRegisterPostError>,
  Options<RegisterUserApiUsersRegisterPostData>
> => {
  const mutationOptions: UseMutationOptions<
    RegisterUserApiUsersRegisterPostResponse,
    AxiosError<RegisterUserApiUsersRegisterPostError>,
    Options<RegisterUserApiUsersRegisterPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await registerUserApiUsersRegisterPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getMeApiUsersUserIdGetQueryKey = (options: Options<GetMeApiUsersUserIdGetData>) =>
  createQueryKey('getMeApiUsersUserIdGet', options);

/**
 * Get Me
 */
export const getMeApiUsersUserIdGetOptions = (options: Options<GetMeApiUsersUserIdGetData>) =>
  queryOptions<
    GetMeApiUsersUserIdGetResponse,
    AxiosError<GetMeApiUsersUserIdGetError>,
    GetMeApiUsersUserIdGetResponse,
    ReturnType<typeof getMeApiUsersUserIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMeApiUsersUserIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMeApiUsersUserIdGetQueryKey(options),
  });

/**
 * Update User Details
 */
export const updateUserDetailsApiUsersUserIdPutMutation = (
  options?: Partial<Options<UpdateUserDetailsApiUsersUserIdPutData>>,
): UseMutationOptions<
  UpdateUserDetailsApiUsersUserIdPutResponse,
  AxiosError<UpdateUserDetailsApiUsersUserIdPutError>,
  Options<UpdateUserDetailsApiUsersUserIdPutData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateUserDetailsApiUsersUserIdPutResponse,
    AxiosError<UpdateUserDetailsApiUsersUserIdPutError>,
    Options<UpdateUserDetailsApiUsersUserIdPutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateUserDetailsApiUsersUserIdPut({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Put User Password
 *
 * Asks for the current password as well, so that a stolen session can't lock the owner out.
 *
 * Signs out every other session. This one gets a new session cookie.
 */
export const putUserPasswordApiUsersUserIdPasswordPutMutation = (
  options?: Partial<Options<PutUserPasswordApiUsersUserIdPasswordPutData>>,
): UseMutationOptions<
  PutUserPasswordApiUsersUserIdPasswordPutResponse,
  AxiosError<PutUserPasswordApiUsersUserIdPasswordPutError>,
  Options<PutUserPasswordApiUsersUserIdPasswordPutData>
> => {
  const mutationOptions: UseMutationOptions<
    PutUserPasswordApiUsersUserIdPasswordPutResponse,
    AxiosError<PutUserPasswordApiUsersUserIdPasswordPutError>,
    Options<PutUserPasswordApiUsersUserIdPasswordPutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putUserPasswordApiUsersUserIdPasswordPut({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
