// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * AuthFeatureFlags
 */
export const zAuthFeatureFlags = z.object({
  password_reset_enabled: z.boolean().default(false),
  user_registration_enabled: z.boolean(),
});

/**
 * AuthFeatureFlagsResponse
 */
export const zAuthFeatureFlagsResponse = z.object({
  data: zAuthFeatureFlags,
});

/**
 * Body_login_for_access_token_api_token_post
 */
export const zBodyLoginForAccessTokenApiTokenPost = z.object({
  client_id: z.string().nullable(),
  client_secret: z.string().nullable(),
  grant_type: z
    .string()
    .regex(/^password$/)
    .nullable(),
  password: z.string(),
  scope: z.string().default(''),
  username: z.string(),
});

/**
 * Body_update_team_logo_api_tournaments__tournament_id__teams__team_id__logo_post
 */
export const zBodyUpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPost = z.object({
  file: z.string().nullable(),
});

/**
 * Body_upload_logo_api_tournaments__tournament_id__logo_post
 */
export const zBodyUploadLogoApiTournamentsTournamentIdLogoPost = z.object({
  file: z.string().nullable(),
});

/**
 * Club
 */
export const zClub = z.object({
  created: z.iso.datetime(),
  id: z.int(),
  name: z.string(),
});

/**
 * ClubCreateBody
 */
export const zClubCreateBody = z.object({
  name: z.string().min(1).max(100),
});

/**
 * ClubResponse
 */
export const zClubResponse = z.object({
  data: zClub.nullable(),
});

/**
 * ClubUpdateBody
 */
export const zClubUpdateBody = z.object({
  name: z.string().min(1).max(100),
});

/**
 * ClubsResponse
 */
export const zClubsResponse = z.object({
  data: z.array(zClub),
});

/**
 * MatchBody
 */
export const zMatchBody = z.object({
  custom_duration_minutes: z.int().gte(1).nullable(),
  custom_margin_minutes: z.int().gte(0).nullable(),
  round_id: z.int(),
  stage_item_input1_score: z.int().gte(0).default(0),
  stage_item_input2_score: z.int().gte(0).default(0),
});

/**
 * MatchCreateBodyFrontend
 */
export const zMatchCreateBodyFrontend = z.object({
  round_id: z.int(),
  stage_item_input1_id: z.int().nullable(),
  stage_item_input1_winner_from_match_id: z.int().nullable(),
  stage_item_input2_id: z.int().nullable(),
  stage_item_input2_winner_from_match_id: z.int().nullable(),
});

/**
 * Player
 */
export const zPlayer = z.object({
  active: z.boolean(),
  created: z.iso.datetime(),
  draws: z.int().default(0),
  elo_score: z
    .string()
    .regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    .default('0.0'),
  id: z.int(),
  losses: z.int().default(0),
  name: z.string(),
  swiss_score: z
    .string()
    .regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    .default('0.0'),
  tournament_id: z.int(),
  wins: z.int().default(0),
});

/**
 * FullTeamWithPlayers
 */
export const zFullTeamWithPlayers = z.object({
  active: z.boolean(),
  created: z.iso.datetime(),
  draws: z.int().default(0),
  elo_score: z
    .string()
    .regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    .default('1200'),
  id: z.int(),
  logo_path: z.string().nullable(),
  losses: z.int().default(0),
  name: z.string(),
  players: z.array(zPlayer),
  swiss_score: z
    .string()
    .regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    .default('0.0'),
  tournament_id: z.int(),
  wins: z.int().default(0),
});

/**
 * PaginatedPlayers
 */
export const zPaginatedPlayers = z.object({
  count: z.int(),
  players: z.array(zPlayer),
});

/**
 * PaginatedTeams
 */
export const zPaginatedTeams = z.object({
  count: z.int(),
  teams: z.array(zFullTeamWithPlayers),
});

/**
 * PlayerBody
 */
export const zPlayerBody = z.object({
  active: z.boolean(),
  name: z.string().min(1).max(30),
});

/**
 * PlayerMultiBody
 */
export const zPlayerMultiBody = z.object({
  active: z.boolean(),
  names: z.string().min(1),
});

/**
 * PlayersResponse
 */
export const zPlayersResponse = z.object({
  data: zPaginatedPlayers,
});

/**
 * Ranking
 */
export const zRanking = z.object({
  add_score_points: z.boolean(),
  created: z.iso.datetime(),
  draw_points: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
  id: z.int(),
  loss_points: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
  position: z.int(),
  tournament_id: z.int(),
  win_points: z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/),
});

/**
 * RankingBody
 */
export const zRankingBody = z.object({
  add_score_points: z.boolean(),
  draw_points: z.union([z.number(), z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)]),
  loss_points: z.union([z.number(), z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)]),
  position: z.int(),
  win_points: z.union([z.number(), z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)]),
});

/**
 * RankingCreateBody
 */
export const zRankingCreateBody = z.object({
  add_score_points: z.boolean().default(false),
  draw_points: z
    .union([z.number(), z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)])
    .default('0.5'),
  loss_points: z
    .union([z.number(), z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)])
    .default('0.0'),
  win_points: z
    .union([z.number(), z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)])
    .default('1.0'),
});

/**
 * RankingsResponse
 */
export const zRankingsResponse = z.object({
  data: z.array(zRanking),
});

/**
 * RoundCreateBody
 */
export const zRoundCreateBody = z.object({
  name: z.string().min(1).max(100).nullable(),
  stage_item_id: z.int(),
});

/**
 * RoundUpdateBody
 */
export const zRoundUpdateBody = z.object({
  is_draft: z.boolean(),
  name: z.string().min(1).max(100),
});

/**
 * SinglePlayerResponse
 */
export const zSinglePlayerResponse = z.object({
  data: zPlayer,
});

/**
 * StageActivateBody
 */
export const zStageActivateBody = z.object({
  direction: z.enum(['next', 'previous']).default('next'),
});

/**
 * StageItemInputEmpty
 */
export const zStageItemInputEmpty = z.object({
  draws: z.int().default(0),
  id: z.int(),
  losses: z.int().default(0),
  points: z
    .string()
    .regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    .default('0.0'),
  slot: z.int(),
  stage_item_id: z.int().nullable(),
  team_id: z.null(),
  tournament_id: z.int(),
  winner_from_stage_item_id: z.null(),
  winner_position: z.null(),
  wins: z.int().default(0),
});

/**
 * StageItemInputOptionFinal
 */
export const zStageItemInputOptionFinal = z.object({
  already_taken: z.boolean(),
  team_id: z.int(),
});

/**
 * StageItemInputOptionTentative
 */
export const zStageItemInputOptionTentative = z.object({
  already_taken: z.boolean(),
  winner_from_stage_item_id: z.int(),
  winner_position: z.int(),
});

/**
 * StageItemInputOptionsResponse
 */
export const zStageItemInputOptionsResponse = z.object({
  data: z.record(
    z.string(),
    z.array(z.union([zStageItemInputOptionTentative, zStageItemInputOptionFinal])),
  ),
});

/**
 * StageItemInputStanding
 */
export const zStageItemInputStanding = z.object({
  draws: z.int().default(0),
  losses: z.int().default(0),
  points: z
    .string()
    .regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    .default('0.00'),
  score_against: z.int().default(0),
  score_for: z.int().default(0),
  stage_item_input_id: z.int(),
  wins: z.int().default(0),
});

/**
 * StageItemInputTentative
 */
export const zStageItemInputTentative = z.object({
  draws: z.int().default(0),
  id: z.int(),
  losses: z.int().default(0),
  points: z
    .string()
    .regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    .default('0.0'),
  slot: z.int(),
  stage_item_id: z.int().nullable(),
  team_id: z.null(),
  tournament_id: z.int(),
  winner_from_stage_item_id: z.int(),
  winner_position: z.int().gte(1),
  wins: z.int().default(0),
});

/**
 * StageItemInputUpdateBodyEmpty
 */
export const zStageItemInputUpdateBodyEmpty = z.object({
  team_id: z.null(),
  winner_from_stage_item_id: z.null(),
  winner_position: z.null(),
});

/**
 * StageItemInputUpdateBodyFinal
 */
export const zStageItemInputUpdateBodyFinal = z.object({
  team_id: z.int(),
});

/**
 * StageItemInputUpdateBodyTentative
 */
export const zStageItemInputUpdateBodyTentative = z.object({
  winner_from_stage_item_id: z.int(),
  winner_position: z.int().gte(1),
});

/**
 * StageItemUpdateBody
 */
export const zStageItemUpdateBody = z.object({
  name: z.string().min(1).max(100),
  ranking_id: z.int(),
});

/**
 * StageType
 */
export const zStageType = z.enum(['ROUND_ROBIN', 'SINGLE_ELIMINATION', 'SWISS']);

/**
 * StageItemCreateBody
 */
export const zStageItemCreateBody = z.object({
  name: z.string().min(1).max(100).nullable(),
  ranking_id: z.int().nullable(),
  stage_id: z.int(),
  team_count: z.int().gte(2).lte(64),
  type: zStageType,
});

/**
 * StageUpdateBody
 */
export const zStageUpdateBody = z.object({
  custom_duration_minutes: z.int().gte(1).nullable(),
  name: z.string().min(1).max(100),
});

/**
 * StandingsResponse
 */
export const zStandingsResponse = z.object({
  data: z.record(z.string(), z.array(zStageItemInputStanding)),
});

/**
 * SuccessResponse
 */
export const zSuccessResponse = z.object({
  success: z.boolean().default(true),
});

/**
 * Team
 */
export const zTeam = z.object({
  active: z.boolean(),
  created: z.iso.datetime(),
  draws: z.int().default(0),
  elo_score: z
    .string()
    .regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    .default('1200'),
  id: z.int(),
  logo_path: z.string().nullable(),
  losses: z.int().default(0),
  name: z.string(),
  swiss_score: z
    .string()
    .regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    .default('0.0'),
  tournament_id: z.int(),
  wins: z.int().default(0),
});

/**
 * SingleTeamResponse
 */
export const zSingleTeamResponse = z.object({
  data: zTeam,
});

/**
 * StageItemInputFinal
 */
export const zStageItemInputFinal = z.object({
  draws: z.int().default(0),
  id: z.int(),
  losses: z.int().default(0),
  points: z
    .string()
    .regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    .default('0.0'),
  slot: z.int(),
  stage_item_id: z.int().nullable(),
  team: zTeam,
  team_id: z.int(),
  tournament_id: z.int(),
  winner_from_stage_item_id: z.int().nullable(),
  winner_position: z.int().nullable(),
  wins: z.int().default(0),
});

/**
 * Match
 */
export const zMatch = z.object({
  created: z.iso.datetime(),
  custom_duration_minutes: z.int().nullable(),
  custom_margin_minutes: z.int().nullable(),
  duration_minutes: z.int(),
  id: z.int(),
  margin_minutes: z.int(),
  round_id: z.int(),
  stage_item_input1: z
    .union([zStageItemInputTentative, zStageItemInputFinal, zStageItemInputEmpty])
    .nullable(),
  stage_item_input1_conflict: z.boolean(),
  stage_item_input1_id: z.int().nullable(),
  stage_item_input1_score: z.int(),
  stage_item_input1_winner_from_match_id: z.int().nullable(),
  stage_item_input2: z
    .union([zStageItemInputTentative, zStageItemInputFinal, zStageItemInputEmpty])
    .nullable(),
  stage_item_input2_conflict: z.boolean(),
  stage_item_input2_id: z.int().nullable(),
  stage_item_input2_score: z.int(),
  stage_item_input2_winner_from_match_id: z.int().nullable(),
  start_time: z.iso.datetime().nullable(),
});

/**
 * MatchWithDetails
 *
 * MatchWithDetails has zero or one defined stage item inputs, but not both.
 */
export const zMatchWithDetails = z.object({
  created: z.iso.datetime(),
  custom_duration_minutes: z.int().nullable(),
  custom_margin_minutes: z.int().nullable(),
  duration_minutes: z.int(),
  id: z.int(),
  margin_minutes: z.int(),
  round_id: z.int(),
  stage_item_input1: z
    .union([zStageItemInputTentative, zStageItemInputFinal, zStageItemInputEmpty])
    .nullable(),
  stage_item_input1_conflict: z.boolean(),
  stage_item_input1_id: z.int().nullable(),
  stage_item_input1_score: z.int(),
  stage_item_input1_winner_from_match_id: z.int().nullable(),
  stage_item_input2: z
    .union([zStageItemInputTentative, zStageItemInputFinal, zStageItemInputEmpty])
    .nullable(),
  stage_item_input2_conflict: z.boolean(),
  stage_item_input2_id: z.int().nullable(),
  stage_item_input2_score: z.int(),
  stage_item_input2_winner_from_match_id: z.int().nullable(),
  start_time: z.iso.datetime().nullable(),
});

/**
 * MatchWithDetailsDefinitive
 */
export const zMatchWithDetailsDefinitive = z.object({
  created: z.iso.datetime(),
  custom_duration_minutes: z.int().nullable(),
  custom_margin_minutes: z.int().nullable(),
  duration_minutes: z.int(),
  id: z.int(),
  margin_minutes: z.int(),
  round_id: z.int(),
  stage_item_input1: z.union([
    zStageItemInputTentative,
    zStageItemInputFinal,
    zStageItemInputEmpty,
  ]),
  stage_item_input1_conflict: z.boolean(),
  stage_item_input1_id: z.int().nullable(),
  stage_item_input1_score: z.int(),
  stage_item_input1_winner_from_match_id: z.int().nullable(),
  stage_item_input2: z.union([
    zStageItemInputTentative,
    zStageItemInputFinal,
    zStageItemInputEmpty,
  ]),
  stage_item_input2_conflict: z.boolean(),
  stage_item_input2_id: z.int().nullable(),
  stage_item_input2_score: z.int(),
  stage_item_input2_winner_from_match_id: z.int().nullable(),
  start_time: z.iso.datetime().nullable(),
});

/**
 * RoundWithMatches
 */
export const zRoundWithMatches = z.object({
  created: z.iso.datetime(),
  id: z.int(),
  is_draft: z.boolean(),
  matches: z.array(z.union([zMatchWithDetailsDefinitive, zMatchWithDetails])),
  name: z.string(),
  stage_item_id: z.int(),
});

/**
 * SingleMatchResponse
 */
export const zSingleMatchResponse = z.object({
  data: zMatch,
});

/**
 * StageItemInputUpdate
 */
export const zStageItemInputUpdate = z.object({
  stage_item_input: zStageItemInputTentative,
  team: zTeam,
});

/**
 * StageItemWithRounds
 */
export const zStageItemWithRounds = z.object({
  created: z.iso.datetime(),
  id: z.int(),
  inputs: z.array(z.union([zStageItemInputTentative, zStageItemInputFinal, zStageItemInputEmpty])),
  name: z.string(),
  ranking_id: z.int().nullable(),
  rounds: z.array(zRoundWithMatches),
  stage_id: z.int(),
  team_count: z.int().gte(2).lte(64),
  type: zStageType,
  type_name: z.string(),
});

/**
 * StageRankingResponse
 */
export const zStageRankingResponse = z.object({
  data: z.record(z.string(), z.array(zStageItemInputUpdate)),
});

/**
 * StageWithStageItems
 */
export const zStageWithStageItems = z.object({
  created: z.iso.datetime(),
  custom_duration_minutes: z.int().gte(1).nullable(),
  id: z.int(),
  is_active: z.boolean(),
  name: z.string(),
  stage_items: z.array(zStageItemWithRounds),
  tournament_id: z.int(),
});

/**
 * StagesWithStageItemsResponse
 */
export const zStagesWithStageItemsResponse = z.object({
  data: z.array(zStageWithStageItems),
});

/**
 * TeamBody
 */
export const zTeamBody = z.object({
  active: z.boolean(),
  name: z.string().min(1).max(30),
  player_ids: z.array(z.int()),
});

/**
 * TeamMultiBody
 */
export const zTeamMultiBody = z.object({
  active: z.boolean(),
  names: z.string().min(1),
});

/**
 * TeamsWithPlayersResponse
 */
export const zTeamsWithPlayersResponse = z.object({
  data: zPaginatedTeams,
});

/**
 * Token
 */
export const zToken = z.object({
  access_token: z.string(),
  name: z.string(),
  token_type: z.string(),
  user_id: z.int(),
});

/**
 * TokenResponse
 */
export const zTokenResponse = z.object({
  data: zToken,
});

/**
 * TournamentBody
 */
export const zTournamentBody = z.object({
  club_id: z.int(),
  dashboard_endpoint: z.string().nullable(),
  dashboard_public: z.boolean(),
  duration_minutes: z.int().gte(1),
  margin_minutes: z.int().gte(0),
  name: z.string().min(1).max(100),
  players_can_be_in_multiple_teams: z.boolean(),
  start_time: z.iso.datetime(),
});

/**
 * TournamentStatus
 */
export const zTournamentStatus = z.enum(['OPEN', 'ARCHIVED']);

/**
 * Tournament
 */
export const zTournament = z.object({
  club_id: z.int(),
  created: z.iso.datetime(),
  dashboard_endpoint: z.string().nullable(),
  dashboard_public: z.boolean(),
  duration_minutes: z.int().gte(1),
  id: z.int(),
  logo_path: z.string().nullable(),
  margin_minutes: z.int().gte(0),
  name: z.string(),
  players_can_be_in_multiple_teams: z.boolean(),
  start_time: z.iso.datetime(),
  status: zTournamentStatus.default('OPEN'),
});

/**
 * TournamentChangeStatusBody
 */
export const zTournamentChangeStatusBody = z.object({
  status: zTournamentStatus,
});

/**
 * TournamentResponse
 */
export const zTournamentResponse = z.object({
  data: zTournament,
});

/**
 * TournamentUpdateBody
 */
export const zTournamentUpdateBody = z.object({
  dashboard_endpoint: z.string().nullable(),
  dashboard_public: z.boolean(),
  duration_minutes: z.int().gte(1),
  margin_minutes: z.int().gte(0),
  name: z.string().min(1).max(100),
  players_can_be_in_multiple_teams: z.boolean(),
  start_time: z.iso.datetime(),
});

/**
 * TournamentsResponse
 */
export const zTournamentsResponse = z.object({
  data: z.array(zTournament),
});

/**
 * UserAccountType
 */
export const zUserAccountType = z.enum(['REGULAR']);

/**
 * UserPasswordToUpdate
 */
export const zUserPasswordToUpdate = z.object({
  current_password: z.string(),
  password: z.string().min(12).max(72),
});

/**
 * UserPublic
 */
export const zUserPublic = z.object({
  account_type: zUserAccountType,
  created: z.iso.datetime(),
  email: z.email(),
  id: z.int(),
  name: z.string(),
});

/**
 * UserPublicResponse
 */
export const zUserPublicResponse = z.object({
  data: zUserPublic,
});

/**
 * UserToRegister
 */
export const zUserToRegister = z.object({
  email: z.email(),
  name: z.string().min(1).max(100),
  password: z.string(),
});

/**
 * UserToUpdate
 */
export const zUserToUpdate = z.object({
  email: z.email(),
  name: z.string().min(1).max(100),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  ctx: z.record(z.string(), z.unknown()).optional(),
  input: z.unknown().optional(),
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
});

/**
 * Successful Response
 */
export const zGetAuthFeaturesApiAuthFeaturesGetResponse = zAuthFeatureFlagsResponse;

/**
 * Successful Response
 */
export const zGetClubsApiClubsGetResponse = zClubsResponse;

export const zCreateNewClubApiClubsPostBody = zClubCreateBody;

/**
 * Successful Response
 */
export const zCreateNewClubApiClubsPostResponse = zClubResponse;

export const zDeleteClubApiClubsClubIdDeletePath = z.object({
  club_id: z.int(),
});

/**
 * Successful Response
 */
export const zDeleteClubApiClubsClubIdDeleteResponse = zSuccessResponse;

export const zUpdateClubApiClubsClubIdPutBody = zClubUpdateBody;

export const zUpdateClubApiClubsClubIdPutPath = z.object({
  club_id: z.int(),
});

/**
 * Successful Response
 */
export const zUpdateClubApiClubsClubIdPutResponse = zClubResponse;

/**
 * Successful Response
 */
export const zLogoutApiLogoutPostResponse = z.void();

/**
 * Response Ping Api Ping Get
 *
 * Successful Response
 */
export const zPingApiPingGetResponse = z.string();

export const zLoginForAccessTokenApiTokenPostBody = zBodyLoginForAccessTokenApiTokenPost;

/**
 * Successful Response
 */
export const zLoginForAccessTokenApiTokenPostResponse = zToken;

export const zGetTournamentsApiTournamentsGetQuery = z.object({
  filter_: z.enum(['ALL', 'OPEN', 'ARCHIVED']).optional().default('OPEN'),
  endpoint_name: z.string().nullish(),
});

/**
 * Successful Response
 */
export const zGetTournamentsApiTournamentsGetResponse = zTournamentsResponse;

export const zCreateTournamentApiTournamentsPostBody = zTournamentBody;

/**
 * Successful Response
 */
export const zCreateTournamentApiTournamentsPostResponse = zSuccessResponse;

export const zDeleteTournamentApiTournamentsTournamentIdDeletePath = z.object({
  tournament_id: z.int(),
});

/**
 * Successful Response
 */
export const zDeleteTournamentApiTournamentsTournamentIdDeleteResponse = zSuccessResponse;

export const zGetTournamentApiTournamentsTournamentIdGetPath = z.object({
  tournament_id: z.int(),
});

/**
 * Successful Response
 */
export const zGetTournamentApiTournamentsTournamentIdGetResponse = zTournamentResponse;

export const zUpdateTournamentByIdApiTournamentsTournamentIdPutBody = zTournamentUpdateBody;

export const zUpdateTournamentByIdApiTournamentsTournamentIdPutPath = z.object({
  tournament_id: z.int(),
});

/**
 * Successful Response
 */
export const zUpdateTournamentByIdApiTournamentsTournamentIdPutResponse = zSuccessResponse;

export const zGetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetPath = z.object({
  tournament_id: z.int(),
});

/**
 * Successful Response
 */
export const zGetAvailableInputsApiTournamentsTournamentIdAvailableInputsGetResponse =
  zStageItemInputOptionsResponse;

export const zChangeStatusApiTournamentsTournamentIdChangeStatusPostBody =
  zTournamentChangeStatusBody;

export const zChangeStatusApiTournamentsTournamentIdChangeStatusPostPath = z.object({
  tournament_id: z.int(),
});

/**
 * Successful Response
 */
export const zChangeStatusApiTournamentsTournamentIdChangeStatusPostResponse = zSuccessResponse;

export const zGetTournamentLogoApiTournamentsTournamentIdLogoGetPath = z.object({
  tournament_id: z.int(),
});

export const zUploadLogoApiTournamentsTournamentIdLogoPostBody =
  zBodyUploadLogoApiTournamentsTournamentIdLogoPost;

export const zUploadLogoApiTournamentsTournamentIdLogoPostPath = z.object({
  tournament_id: z.int(),
});

/**
 * Successful Response
 */
export const zUploadLogoApiTournamentsTournamentIdLogoPostResponse = zTournamentResponse;

export const zCreateMatchApiTournamentsTournamentIdMatchesPostBody = zMatchCreateBodyFrontend;

export const zCreateMatchApiTournamentsTournamentIdMatchesPostPath = z.object({
  tournament_id: z.int(),
});

/**
 * Successful Response
 */
export const zCreateMatchApiTournamentsTournamentIdMatchesPostResponse = zSingleMatchResponse;

export const zDeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeletePath = z.object({
  tournament_id: z.int(),
  match_id: z.int(),
});

/**
 * Successful Response
 */
export const zDeleteMatchApiTournamentsTournamentIdMatchesMatchIdDeleteResponse = zSuccessResponse;

export const zUpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutBody = zMatchBody;

export const zUpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutPath = z.object({
  tournament_id: z.int(),
  match_id: z.int(),
});

/**
 * Successful Response
 */
export const zUpdateMatchByIdApiTournamentsTournamentIdMatchesMatchIdPutResponse = zSuccessResponse;

export const zGetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetPath = z.object({
  tournament_id: z.int(),
});

/**
 * Successful Response
 */
export const zGetNextStageRankingsApiTournamentsTournamentIdNextStageRankingsGetResponse =
  zStageRankingResponse;

export const zGetPlayersApiTournamentsTournamentIdPlayersGetPath = z.object({
  tournament_id: z.int(),
});

export const zGetPlayersApiTournamentsTournamentIdPlayersGetQuery = z.object({
  not_in_team: z.boolean().optional().default(false),
  limit: z.int().gte(1).lte(500).optional().default(25),
  offset: z.int().gte(0).optional().default(0),
  sort_direction: z.enum(['asc', 'desc']).optional().default('asc'),
  sort_by: z
    .enum(['name', 'elo_score', 'swiss_score', 'wins', 'draws', 'losses', 'active', 'created'])
    .optional()
    .default('name'),
});

/**
 * Successful Response
 */
export const zGetPlayersApiTournamentsTournamentIdPlayersGetResponse = zPlayersResponse;

export const zCreateSinglePlayerApiTournamentsTournamentIdPlayersPostBody = zPlayerBody;

export const zCreateSinglePlayerApiTournamentsTournamentIdPlayersPostPath = z.object({
  tournament_id: z.int(),
});

/**
 * Successful Response
 */
export const zCreateSinglePlayerApiTournamentsTournamentIdPlayersPostResponse = zSuccessResponse;

export const zDeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeletePath = z.object({
  tournament_id: z.int(),
  player_id: z.int(),
});

/**
 * Successful Response
 */
export const zDeletePlayerApiTournamentsTournamentIdPlayersPlayerIdDeleteResponse =
  zSuccessResponse;

export const zUpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutBody = zPlayerBody;

export const zUpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutPath = z.object({
  tournament_id: z.int(),
  player_id: z.int(),
});

/**
 * Successful Response
 */
export const zUpdatePlayerByIdApiTournamentsTournamentIdPlayersPlayerIdPutResponse =
  zSinglePlayerResponse;

export const zCreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostBody =
  zPlayerMultiBody;

export const zCreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostPath = z.object({
  tournament_id: z.int(),
});

/**
 * Successful Response
 */
export const zCreateMultiplePlayersApiTournamentsTournamentIdPlayersMultiPostResponse =
  zSuccessResponse;

export const zGetRankingsApiTournamentsTournamentIdRankingsGetPath = z.object({
  tournament_id: z.int(),
});

/**
 * Successful Response
 */
export const zGetRankingsApiTournamentsTournamentIdRankingsGetResponse = zRankingsResponse;

export const zCreateRankingApiTournamentsTournamentIdRankingsPostBody = zRankingCreateBody;

export const zCreateRankingApiTournamentsTournamentIdRankingsPostPath = z.object({
  tournament_id: z.int(),
});

/**
 * Successful Response
 */
export const zCreateRankingApiTournamentsTournamentIdRankingsPostResponse = zSuccessResponse;

export const zDeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeletePath = z.object({
  tournament_id: z.int(),
  ranking_id: z.int(),
});

/**
 * Successful Response
 */
export const zDeleteRankingApiTournamentsTournamentIdRankingsRankingIdDeleteResponse =
  zSuccessResponse;

export const zUpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutBody = zRankingBody;

export const zUpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutPath = z.object({
  tournament_id: z.int(),
  ranking_id: z.int(),
});

/**
 * Successful Response
 */
export const zUpdateRankingByIdApiTournamentsTournamentIdRankingsRankingIdPutResponse =
  zSuccessResponse;

export const zCreateRoundApiTournamentsTournamentIdRoundsPostBody = zRoundCreateBody;

export const zCreateRoundApiTournamentsTournamentIdRoundsPostPath = z.object({
  tournament_id: z.int(),
});

/**
 * Successful Response
 */
export const zCreateRoundApiTournamentsTournamentIdRoundsPostResponse = zSuccessResponse;

export const zDeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeletePath = z.object({
  tournament_id: z.int(),
  round_id: z.int(),
});

/**
 * Successful Response
 */
export const zDeleteRoundApiTournamentsTournamentIdRoundsRoundIdDeleteResponse = zSuccessResponse;

export const zUpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutBody = zRoundUpdateBody;

export const zUpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutPath = z.object({
  tournament_id: z.int(),
  round_id: z.int(),
});

/**
 * Successful Response
 */
export const zUpdateRoundByIdApiTournamentsTournamentIdRoundsRoundIdPutResponse = zSuccessResponse;

export const zScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostPath = z.object({
  tournament_id: z.int(),
});

/**
 * Successful Response
 */
export const zScheduleMatchesApiTournamentsTournamentIdScheduleMatchesPostResponse =
  zSuccessResponse;

export const zCreateStageItemApiTournamentsTournamentIdStageItemsPostBody = zStageItemCreateBody;

export const zCreateStageItemApiTournamentsTournamentIdStageItemsPostPath = z.object({
  tournament_id: z.int(),
});

/**
 * Successful Response
 */
export const zCreateStageItemApiTournamentsTournamentIdStageItemsPostResponse = zSuccessResponse;

export const zDeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeletePath = z.object({
  tournament_id: z.int(),
  stage_item_id: z.int(),
});

/**
 * Successful Response
 */
export const zDeleteStageItemApiTournamentsTournamentIdStageItemsStageItemIdDeleteResponse =
  zSuccessResponse;

export const zUpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutBody =
  zStageItemUpdateBody;

export const zUpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutPath = z.object({
  tournament_id: z.int(),
  stage_item_id: z.int(),
});

/**
 * Successful Response
 */
export const zUpdateStageItemApiTournamentsTournamentIdStageItemsStageItemIdPutResponse =
  zSuccessResponse;

/**
 * Stage Item Body
 */
export const zUpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutBody =
  z.union([
    zStageItemInputUpdateBodyTentative,
    zStageItemInputUpdateBodyFinal,
    zStageItemInputUpdateBodyEmpty,
  ]);

export const zUpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutPath =
  z.object({
    tournament_id: z.int(),
    stage_item_id: z.int(),
    stage_item_input_id: z.int(),
  });

/**
 * Successful Response
 */
export const zUpdateStageItemInputApiTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponse =
  zSuccessResponse;

export const zGetStagesApiTournamentsTournamentIdStagesGetPath = z.object({
  tournament_id: z.int(),
});

export const zGetStagesApiTournamentsTournamentIdStagesGetQuery = z.object({
  no_draft_rounds: z.boolean().optional().default(false),
});

/**
 * Successful Response
 */
export const zGetStagesApiTournamentsTournamentIdStagesGetResponse = zStagesWithStageItemsResponse;

export const zCreateStageApiTournamentsTournamentIdStagesPostPath = z.object({
  tournament_id: z.int(),
});

/**
 * Successful Response
 */
export const zCreateStageApiTournamentsTournamentIdStagesPostResponse = zSuccessResponse;

export const zActivateNextStageApiTournamentsTournamentIdStagesActivatePostBody =
  zStageActivateBody;

export const zActivateNextStageApiTournamentsTournamentIdStagesActivatePostPath = z.object({
  tournament_id: z.int(),
});

/**
 * Successful Response
 */
export const zActivateNextStageApiTournamentsTournamentIdStagesActivatePostResponse =
  zSuccessResponse;

export const zDeleteStageApiTournamentsTournamentIdStagesStageIdDeletePath = z.object({
  tournament_id: z.int(),
  stage_id: z.int(),
});

/**
 * Successful Response
 */
export const zDeleteStageApiTournamentsTournamentIdStagesStageIdDeleteResponse = zSuccessResponse;

export const zUpdateStageApiTournamentsTournamentIdStagesStageIdPutBody = zStageUpdateBody;

export const zUpdateStageApiTournamentsTournamentIdStagesStageIdPutPath = z.object({
  tournament_id: z.int(),
  stage_id: z.int(),
});

/**
 * Successful Response
 */
export const zUpdateStageApiTournamentsTournamentIdStagesStageIdPutResponse = zSuccessResponse;

export const zGetStandingsApiTournamentsTournamentIdStandingsGetPath = z.object({
  tournament_id: z.int(),
});

/**
 * Successful Response
 */
export const zGetStandingsApiTournamentsTournamentIdStandingsGetResponse = zStandingsResponse;

export const zGetTeamsApiTournamentsTournamentIdTeamsGetPath = z.object({
  tournament_id: z.int(),
});

export const zGetTeamsApiTournamentsTournamentIdTeamsGetQuery = z.object({
  limit: z.int().gte(1).lte(500).optional().default(25),
  offset: z.int().gte(0).optional().default(0),
  sort_direction: z.enum(['asc', 'desc']).optional().default('asc'),
  sort_by: z
    .enum(['name', 'elo_score', 'swiss_score', 'wins', 'draws', 'losses', 'active', 'created'])
    .optional()
    .default('name'),
});

/**
 * Successful Response
 */
export const zGetTeamsApiTournamentsTournamentIdTeamsGetResponse = zTeamsWithPlayersResponse;

export const zCreateTeamApiTournamentsTournamentIdTeamsPostBody = zTeamBody;

export const zCreateTeamApiTournamentsTournamentIdTeamsPostPath = z.object({
  tournament_id: z.int(),
});

/**
 * Successful Response
 */
export const zCreateTeamApiTournamentsTournamentIdTeamsPostResponse = zSingleTeamResponse;

export const zDeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeletePath = z.object({
  tournament_id: z.int(),
  team_id: z.int(),
});

/**
 * Successful Response
 */
export const zDeleteTeamApiTournamentsTournamentIdTeamsTeamIdDeleteResponse = zSuccessResponse;

export const zUpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutBody = zTeamBody;

export const zUpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutPath = z.object({
  tournament_id: z.int(),
  team_id: z.int(),
});

/**
 * Successful Response
 */
export const zUpdateTeamByIdApiTournamentsTournamentIdTeamsTeamIdPutResponse = zSingleTeamResponse;

export const zGetTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoGetPath = z.object({
  tournament_id: z.int(),
  team_id: z.int(),
});

export const zUpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostBody =
  zBodyUpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPost;

export const zUpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostPath = z.object({
  tournament_id: z.int(),
  team_id: z.int(),
});

/**
 * Successful Response
 */
export const zUpdateTeamLogoApiTournamentsTournamentIdTeamsTeamIdLogoPostResponse =
  zSingleTeamResponse;

export const zCreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostBody = zTeamMultiBody;

export const zCreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostPath = z.object({
  tournament_id: z.int(),
});

/**
 * Successful Response
 */
export const zCreateMultipleTeamsApiTournamentsTournamentIdTeamsMultiPostResponse =
  zSuccessResponse;

/**
 * Successful Response
 */
export const zGetUserApiUsersMeGetResponse = zUserPublicResponse;

export const zRegisterUserApiUsersRegisterPostBody = zUserToRegister;

/**
 * Successful Response
 */
export const zRegisterUserApiUsersRegisterPostResponse = zTokenResponse;

export const zGetMeApiUsersUserIdGetPath = z.object({
  user_id: z.int(),
});

/**
 * Successful Response
 */
export const zGetMeApiUsersUserIdGetResponse = zUserPublicResponse;

export const zUpdateUserDetailsApiUsersUserIdPutBody = zUserToUpdate;

export const zUpdateUserDetailsApiUsersUserIdPutPath = z.object({
  user_id: z.int(),
});

/**
 * Successful Response
 */
export const zUpdateUserDetailsApiUsersUserIdPutResponse = zUserPublicResponse;

export const zPutUserPasswordApiUsersUserIdPasswordPutBody = zUserPasswordToUpdate;

export const zPutUserPasswordApiUsersUserIdPasswordPutPath = z.object({
  user_id: z.int(),
});

/**
 * Successful Response
 */
export const zPutUserPasswordApiUsersUserIdPasswordPutResponse = zSuccessResponse;
